export const image = {
    splash: require('../../assets/Splash_image.jpeg'),
    eyclose: require('../../assets/eyeclose.png'),
    eyeopen: require('../../assets/eyeopen.png'),
    admin: require('../../assets/user.png'),
    password: require('../../assets/padlock.png'),
    email: require('../../assets/email.png'),
    name: require('../../assets/id-card.png'),
    fuelStation: require('../../assets/fuelonlogo.png'),
    rectangle: require('../../assets/rectangle.png'),
    search: require('../../assets/search.png'),
    fuel: require('../../assets/gas-station_1.png'),
    diesel: require('../../assets/gasoline.png'),
    gas: require('../../assets/gas.jpg'),
    mechanic: require('../../assets/maintenance.png'),
    puncture: require('../../assets/punctured-tire.png'),
    notification: require('../../assets/Notification.png'),
    backicon: require('../../assets/backicon.png'),
    home: require('../../assets/home.png'),
    account: require('../../assets/account.png'),
    forward: require('../../assets/right-arrows.png'),
    lpg: require('../../assets/lpg.png'),
    cng: require('../../assets/CNG-Logo-Transparent-PNG.png'),
    bio_diesel: require('../../assets/bio-diesel.png'),
    ethanol: require('../../assets/ethanol.png'),
    location: require('../../assets/location.png'),
    radio: require('../../assets/radio-button.png'),
    radioPressed: require('../../assets/radioPressed.png'),
    gpay:require('../../assets/google-pay.png'),
    phonepe:require('../../assets/pngwing.com.png'),
    paytm:require('../../assets/paytm.png'),
    visa:require('../../assets/Visacard.png'),
    mastercard:require('../../assets/mastercard.png'),
    rupay:require('../../assets/Rupay.png'),
    about:require('../../assets/information-button.png'),
    contact:require('../../assets/phone.png'),
    privacy:require('../../assets/shield.png'),
    conditions:require('../../assets/terms-and-conditions.png'),
    phoneCall:require('../../assets/phone-call.png'),
    check:require('../../assets/check-mark.png'),

}